#!/usr/bin/env bash

# Copyright (c) 2020 Federico Kircheis

# Permission to use, copy, modify, and distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

set -o errexit
set -o nounset
set -o pipefail # the main reason why using bash and not sh as shell

main () {
  if { [ ! -t 1 ] && [ -z ${COLORIZE_SVN_FORCE+x} ]; } || [ $# -eq 0 ] ; then :;
    exec svn "$@";
  fi

  for arg in "$@"; do :;
    if [ "$arg" = "--help" ] || [ "$arg" = "help" ] || [ "$arg" = "h" ] || [ "$arg" = "-h" ] || [ "$arg" = "-?" ]; then :;
      exec svn "$@" | colorize-svn --page-only;
      return;
    fi
  done

  if [ "$1" = "up" ] || [ "$1" = "update" ]; then :;
    shift 1;
    svn update --non-interactive "$@" | colorize-svn;
    return;
  elif [ "$1" = "st" ] || [ "$1" = "stat" ] || [ "$1" = "status" ] ; then :;
    svn "$@" | LC_ALL=C sort | sed 's|\\|/|' | colorize-svn --files --no-log --no-diff;
    return;
  elif [ "$1" = "diff" ] || [ "$1" = "di" ] ; then :;
    svn "$@" | colorize-svn --diff --no-log --no-files;
    return;
  elif [ "$1" = "log" ] ; then :;
    for arg in "$@"; do :;
      if [ "$arg" = "--diff" ]; then :;
         svn "$@" | colorize-svn --log --diff;
         return;
      fi
     done
    svn "$@" | colorize-svn --log --no-diff;
    return;
  elif [ "$1" = "annotate" ] || [ "$1" = "ann" ] \
    || [ "$1" = "praise" ] || [ "$1" = "blame" ] ; then :;
    svn "$@" | colorize-svn --annotate;
    return;
  elif [ "$1" = "add" ] \
    || [ "$1" = "co" ] || [ "$1" = "checkout" ] \
    || [ "$1" = "del" ] || [ "$1" = "delete" ] \
    || [ "$1" = "rm" ] || [ "$1" = "remove" ] \
    || [ "$1" = "mv" ] || [ "$1" = "move" ] \
    || [ "$1" = "ren" ] || [ "$1" = "rename" ]; then :;
    svn "$@" | colorize-svn --no-pager;
    return;
  else
    exec svn "$@";
  fi
}

main "$@";
